---

# image will be published to ghcr.io/<user>/<name>
name: mystation
# description will be included in the image's metadata
description: A continually improved Cloud Native Desktop OS. https://github.com/aussielunix/mystation

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
    install:
      - bootc
      - cloud-utils-cloud-localds
      - code
      - devpod
      - iotop
      - jetbrains-mono-fonts-all
      - langpacks-en
      - libvirt
      - mc
      - nmap
      - podman-compose
      - podmansh
      - qemu-char-spice
      - qemu-device-display-virtio-gpu
      - qemu-device-display-virtio-vga
      - qemu-device-usb-redirect
      - qemu-img
      - qemu-system-x86-core
      - qemu-user-binfmt
      - qemu-user-static
      - qemu
      - strace
      - terminator
      - vim-enhanced
      - virt-install
      - virt-manager
      - virt-viewer
      - webkit2gtk4.0
      - wl-clipboard
      - yubikey-manager-qt
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - passim
  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - com.discordapp.Discord
        - org.keepassxc.KeePassXC
        - org.mozilla.firefox
        - org.tigervnc.vncviewer
        - org.videolan.VLC
      remove: []
  - type: gnome-extensions
    install:
      - space-barluchrioh.v25
      - just-perfection-desktopjust-perfection.v28
      - appindicatorsupportrgcjonas.gmail.com.v58
  - type: systemd
    system:
      disabled:
        - cups
      masked:
        - cups
  - type: signing
