---

# image will be published to ghcr.io/<user>/<name>
name: mystation
# description will be included in the image's metadata
description: A continually improved Cloud Native Desktop OS. https://github.com/aussielunix/mystation

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 38 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
  - type: rpm-ostree
    install:
      - devpod
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-just-perfection
      - jetbrains-mono-fonts-all
      - langpacks-en
      - mc
      - strace
      - terminator
      - vim-enhanced
      - yubikey-manager-qt
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks
  # https://github.com/ublue-os/bling
  - type: bling
    install:
      - justfiles
  - type: yafti
    custom-flatpaks:
      - KeePassXC: org.keepassxc.KeePassXC
      - Firefox: org.mozilla.firefox
      - VSCodium: com.vscodium.codium
  - type: script
    scripts:
      - signing.sh
