# image will be published to ghcr.io/<user>/<name>
name: mystation
# description will be included in the image's metadata
description: A continually improved Cloud Native Desktop OS. https://github.com/aussielunix/mystation

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
    install:
      - devpod
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-just-perfection
      - jetbrains-mono-fonts-all
      - langpacks-en
      - mc
      - strace
      - terminator
      - vim-enhanced
      - yubikey-manager-qt
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - KeePassXC: org.keepassxc.KeePassXC
        - Firefox: org.mozilla.firefox
        - VSCode: com.visualstudio.code
        - Discord: com.discordapp.Discord
        - TigerVNC: com.tigervnc.vncviewer
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

