---

# image will be published to ghcr.io/<user>/<name>
name: mystation
# description will be included in the image's metadata
description: A continually improved Cloud Native Desktop OS. https://github.com/aussielunix/mystation

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
  - type: rpm-ostree
    install:
      - devpod
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-just-perfection
      - jetbrains-mono-fonts-all
      - langpacks-en
      - mc
      - strace
      - terminator
      - vim-enhanced
      - yubikey-manager-qt
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks

  - type: default-flatpaks
    notify: true   # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - KeePassXC: org.keepassxc.KeePassXC
        - Firefox: org.mozilla.firefox
        - VSCodium: com.vscodium.codium
        - Discord: com.discordapp.Discord
      remove:
      # - org.gnome.eog
      #
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub

  - type: script
    scripts:
      - signing.sh
